create table if not exists public.cherry_chase_scores (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 10),
  score integer not null check (score >= 0),
  level integer not null check (level >= 1),
  result text not null,
  created_at timestamptz not null default now()
);

alter table public.cherry_chase_scores enable row level security;

create policy "public can read scores"
on public.cherry_chase_scores
for select
to anon
using (true);

create policy "public can insert scores"
on public.cherry_chase_scores
for insert
to anon
with check (true);
